[[main]]
    # Top-level menu entry
    identifier = "work"
    name = "Work"
    url = "/projects/"
    weight = 1

[[main]]
    identifier = "robocon"
    name = "Robocon"
    url = "/robocon/"
    parent = "work"
    weight = 12

[[main]]
    identifier = "sponsor"
    name = "Sponsor"
    url = "/sponsor/"
    parent = "explore"
    weight = 13

[[main]]
    identifier = "awards"
    name = "Awards"
    url = "/awards/"
    parent = "explore"
    weight = 14

[[main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    parent = "work"
    weight = 2

[[main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    parent = "work"
    weight = 3


[[main]]
    # Top-level menu entry
    identifier = "explore"
    name = "Explore"
    url = "/categories/"
    weight = 6

[[main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    parent = "explore"
    weight = 7

[[main]]
    # Top-level menu entry
    identifier = "reach us"
    name = "Reach Us"
    url = "/about/"
    weight = 8

[[main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    parent = "reach us"
    weight = 9

[[main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    parent = "reach us"
    weight = 10

